name: Build and Deploy Backend

on:
  push:
    paths:
      - 'server/**'
    branches:
      - main

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker to use the Google Container Registry
        run: gcloud auth configure-docker gcr.io

      - name: Build and push backend Docker image
        run: |
          docker build -t gcr.io/your-project-id/live-feed-server:latest ./server
          docker push gcr.io/your-project-id/live-feed-server:latest

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY }}

      - name: Deploy backend container on VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_SSH_USER }}@${{ secrets.VM_SSH_HOST }} << EOF
            docker pull gcr.io/your-project-id/live-feed-server:latest
            docker stop live-feed-server || true
            docker rm live-feed-server || true
            docker run -d --restart unless-stopped --name live-feed-server -p 5000:5000 \
              -e DATABASE_URL=postgresql://postgres:postgres@35.194.27.38:5432/live_feed \
              gcr.io/your-project-id/live-feed-server:latest
          EOF
