name: Build and Deploy Frontend

on:
  push:
    paths:
      - 'client/**'
    branches:
      - main

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker to use the Google Container Registry
        run: gcloud auth configure-docker gcr.io

      - name: Build and push frontend Docker image
        run: |
          docker build -t gcr.io/your-project-id/live-feed-client:latest ./client
          docker push gcr.io/your-project-id/live-feed-client:latest

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY }}

      - name: Deploy frontend container on VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_SSH_USER }}@${{ secrets.VM_SSH_HOST }} << EOF
            docker pull gcr.io/your-project-id/live-feed-client:latest
            docker stop live-feed-client || true
            docker rm live-feed-client || true
            docker run -d --restart unless-stopped --name live-feed-client -p 80:80 \
              gcr.io/your-project-id/live-feed-client:latest
          EOF
